require "bundler/setup"
require "aws-sdk-s3"
require "json"
require "kubeclient"
require "open-uri"
require "openid_connect"

require "#{File.dirname(__FILE__)}/orphaned_namespace_checker/cloud_platform_orphaned_namespaces"
require "#{File.dirname(__FILE__)}/orphaned_namespace_checker/kubeconfig"
require "#{File.dirname(__FILE__)}/orphaned_namespace_checker/cluster_namespace_lister"
