name: Rspec Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby 3.1.3
      uses: ruby/setup-ruby@v1

    - name: Install gems
      run: |
        gem install bundler
        bundle install

    - name: Run specs
      run: |
        bundle exec rspec
